### 1. Create a 3x3 array that contains a diagonal of nines.

In [4]:
import numpy as np

np1 = np.array([[9, 0, 0],
                [0, 9, 0], 
                [0, 0, 9]])
print(np1)

# OR

np2 = np.diag([9, 9, 9])
print(np2)

[[9 0 0]
 [0 9 0]
 [0 0 9]]
[[9 0 0]
 [0 9 0]
 [0 0 9]]


### 2. Create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32 (inclusive) and use Boolean indexing to pick out the values that are within 1/2 standard deviations of the mean.

In [60]:
import numpy as np

np1 = np.arange(2, 33, 2).reshape((4, 4))
std = np1.std()

bool_np = np1 > std
print(np1)
print(bool_np)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


### 3. Create a 9x9 array that contains only zero of type int.

In [59]:
import numpy as np

np1 = np.zeros((9, 9))
print(np1)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### 4. Ask the user for a number n. Then, use broadcasting to create a n x n ndarray that has its first column full of ones, its second column full of twos, its third column full of threes, etc…

In [62]:
import numpy as np

n = int(input())
np1 = np.arange(1, n + 1)
result = np.tile(np1, (n, 1))
print(result)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]


### 5. A. Sereja and Dima 
https://codeforces.com/contest/381/problem/A

In [58]:
import numpy as np

n = int(input())
np1 = np.array(list(map(int, input().split())))

i = 0
j = n - 1
serejaturn = True
sereja = 0
dima = 0

while i <= j:
    if np1[i] > np1[j]:
        if serejaturn:
            sereja += np1[i]
        else:
            dima += np1[i]
        i += 1
    else:
        if serejaturn:
            sereja += np1[j]
        else:
            dima += np1[j]
        j -= 1
    serejaturn = not serejaturn

print(sereja, dima)    

9 6


### 6. A. Brain's Photos
https://codeforces.com/contest/707/problem/A

In [ ]:
import numpy as np

rows, cols = map(int, input().split())
np1 = np.array([input().split() for _ in range(rows)])

for row in np1:
    if any(pixel in 'CMYG' for pixel in row):
        print("#Color")
        break
else:
    print("#Black&White")